apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: development
  labels:
    name: nginx
    app: nginx
spec:
  replicas: 1
  selector:
      matchLabels:
        name: nginx
  template:
    metadata:
      labels:
        name: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
