apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: development
  labels:
    name: nginx
    app: nginx
spec:
  selector:
    name: nginx
  type: ClusterIP
  ports:
   - name: http
     port: 80
     targetPort: 80
     protocol: TCP
